language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2.0
- 2.3.0
- 2.4.0
- 2.5.0
- 2.6.0
- jruby
- rubinius
- truffleruby
matrix:
  allow_failures:
  - rvm: rubinius
  - rvm: truffleruby
branches:
  only:
  - master
script:
- rake
after_script:
- rake evaluate
