language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
branches:
  only:
    - master
before_install:
  - gem install bundler
script:
  - rake
  - rake evaluate
  - rake detect
