language: ruby
rvm:
- '1.9.3'
- '2.0'
- '2.1'
- '2.2'
- '2.3'
- '2.4'
- '2.5'
- '2.6'
- '2.7'
- ruby-head
- jruby
- truffleruby
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: truffleruby
script:
- rake
after_script:
- rake evaluate
